<a href="https://colab.research.google.com/github/abhinavverma0907/SOC-2026-Encryption-and-Decryption/blob/main/Week_0/Assignment_1/Q1_Finding_the_Killer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np

people = pd.read_csv('/content/drive/MyDrive/SOC-2026/Assignment-1/Q1/unique_people_dataset_2000.csv')
teachers   = pd.read_csv('/content/drive/MyDrive/SOC-2026/Assignment-1/Q1/all_teacher.csv')

people.head()

             name  age  height  weight occupation    location
0   Jeffrey Mason   59   173.0    97.1    Teacher  city_north
1     Gina Deleon   69   149.8    97.2   Mechanic   city_west
2  Victoria Davis   54   171.2    60.0      Pilot   city_west
3   Angela Torres   46   162.7    72.7  Scientist  city_north
4       Tara Pace   58   197.4    51.1    Analyst   city_east

In [3]:
teachers.head()

              name  age  height  weight occupation    location  Joining year
0    Jeffrey Mason   59   173.0    97.1    Teacher  city_north          2005
1  Nicholas Rivera   37   147.7    98.4    Teacher   city_east          2005
2   John Armstrong   38   169.0    62.0    Teacher  city_north          2018
3       John Yates   27   160.8    92.8    Teacher   city_west          2001
4     Joseph Colon   42   198.5    54.2    Teacher   city_west          2018