<a href="https://colab.research.google.com/github/abhinavverma0907/SOC-2026-Encryption-and-Decryption/blob/main/Week_0/Assignment_1/Q1_Finding_the_Killer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q1 Finding the Killer

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import pandas as pd
import numpy as np

people = pd.read_csv('/content/drive/MyDrive/SOC-2026/Assignment-1/Q1/unique_people_dataset_2000.csv')
teachers   = pd.read_csv('/content/drive/MyDrive/SOC-2026/Assignment-1/Q1/all_teacher.csv')

people.head()

             name  age  height  weight occupation    location
0   Jeffrey Mason   59   173.0    97.1    Teacher  city_north
1     Gina Deleon   69   149.8    97.2   Mechanic   city_west
2  Victoria Davis   54   171.2    60.0      Pilot   city_west
3   Angela Torres   46   162.7    72.7  Scientist  city_north
4       Tara Pace   58   197.4    51.1    Analyst   city_east

In [6]:
teachers.head()

              name  age  height  weight occupation    location  Joining year
0    Jeffrey Mason   59   173.0    97.1    Teacher  city_north          2005
1  Nicholas Rivera   37   147.7    98.4    Teacher   city_east          2005
2   John Armstrong   38   169.0    62.0    Teacher  city_north          2018
3       John Yates   27   160.8    92.8    Teacher   city_west          2001
4     Joseph Colon   42   198.5    54.2    Teacher   city_west          2018

##Suspect filtering on people

In [10]:
suspects = people[
    (people['age'] >= 30) & (people['age'] <= 45) &
    (people['height'] >= 160) & (people['height'] <= 190) &
    (people['weight'] >= 50) & (people['weight'] <= 100) &
    (people['location'].isin(['city_south']))
]
print('Number of suspects:', suspects.shape[0])
suspects

Number of suspects so far: 48

                     name  age  height  weight    occupation    location
12        Patricia Walker   34   170.2    75.8     Architect  city_south
123     Brittany Gonzalez   44   183.1    68.9      Mechanic  city_south
124           Lisa Chavez   32   183.4    59.4       Analyst  city_south
130            Ryan Davis   45   160.1    85.1        Writer  city_south
168          Regina Smith   37   164.8    86.8       Analyst  city_south
200   Christopher Jackson   33   166.7    77.2        Writer  city_south
286     William Patterson   35   160.6    84.7        Artist  city_south
330         David Stevens   45   187.1    96.9     Developer  city_south
359            Daniel Cox   32   164.2    98.0        Artist  city_south
452      Connie Alexander   37   168.6    66.5        Writer  city_south
551         Patricia Lang   44   167.4    65.5        Doctor  city_south
605       Kristen Hendrix   30   188.4    60.5     Scientist  city_south
712      Katelyn Thompson   38   170.7    61.9       Student  city_south
813            Brian Neal   40   161.3    95.9   Electrician  city_south
878        Ashlee Ramirez   33   163.9    79.7        Doctor  city_south
972     Michelle Bauer MD   34   165.7    94.4         Nurse  city_south
979       Cameron Simpson   40   176.9    64.7         Pilot  city_south
1046        Robert Mccann   40   160.5    55.6        Lawyer  city_south
1122     Melanie Trujillo   36   184.4    79.2  Photographer  city_south
1158     Gregory Richards   43   187.6    88.1     Scientist  city_south
1224     Meghan Dennis MD   43   160.2    79.4      Engineer  city_south
1230         Darren Jones   31   172.8    74.8       Student  city_south
1243        Susan Gilbert   34   180.2    76.6       Analyst  city_south
1319       Mrs. Sue Perez   32   181.3    53.3  Photographer  city_south
1338        Justin Chavez   30   161.5    75.3    Consultant  city_south
1353        Laura Freeman   40   179.2    67.9     Architect  city_south
1369    Courtney Olson MD   43   178.1    65.0        Writer  city_south
1373  Christopher Nichols   41   169.1    97.9     Developer  city_south
1395           Mary Casey   34   181.2    65.3  Photographer  city_south
1414          Brett Smith   41   181.8    95.6   Electrician  city_south
1528   Jennifer Daugherty   33   170.3    61.2         Pilot  city_south
1529            Amy Green   44   176.9    56.6    Consultant  city_south
1664           Eric Dixon   39   168.7    91.0     Architect  city_south
1725       William Decker   43   174.7    90.5    Consultant  city_south
1731        Amy Robertson   37   166.6    67.2        Artist  city_south
1740        Brandon Salas   41   175.8    52.1        Lawyer  city_south
1741      Kristine Bright   44   171.4    63.5        Writer  city_south
1749           Beth Jones   41   184.0    72.3  Photographer  city_south
1766          Jerry Jones   37   181.1    95.9      Mechanic  city_south
1774      Leslie Chambers   32   170.9    52.8   Electrician  city_south
1812        John Robinson   35   161.7    68.7        Doctor  city_south
1837          James Kelly   37   167.2    71.6        Lawyer  city_south
1856         Kevin Lozano   45   177.4    75.8          Chef  city_south
1922        Marvin Morgan   43   166.2    63.3  Photographer  city_south
1952       Carol Williams   41   169.7    70.1         Nurse  city_south
1963            Kerry Day   45   169.3    83.0      Mechanic  city_south
1978        Jhon Williams   44   169.4    85.9       Teacher  city_south
1989           Lori Clark   44   180.2    51.9       Analyst  city_south

##Suspect filtering on teachers

In [9]:
suspects = teachers[
    (teachers['age'] >= 30) & (teachers['age'] <= 45) &
    (teachers['height'] >= 160) & (teachers['height'] <= 190) &
    (teachers['weight'] >= 50) & (teachers['weight'] <= 100) &
    (teachers['location'].isin(['city_south']))
]
print('Number of suspects:', suspects.shape[0])
suspects

Number of suspects so far: 1

             name  age  height  weight occupation    location  Joining year
82  Jhon Williams   44   169.4    85.9    Teacher  city_south          2010

##"close friend since long"

In [8]:
suspects = suspects[suspects['Joining year'] <= 2014]
print('After joining-year filter:', suspects.shape[0])
suspects

After joining-year filter: 1

             name  age  height  weight occupation    location  Joining year
82  Jhon Williams   44   169.4    85.9    Teacher  city_south          2010